### ISSUE TITLE
Work In Reverse

### ISSUE THREAD

**Issue by NatESkiN** [trendwerk/post-type-as-taxonomy#1]
It works perfectly, but I think it would be a good idea to also work in reverse. If you add a content taxonomy, which also appears as content in the post type.

The CPT-onomies plugin works this way, but it seems a very heavy plugin and this kind seems perfect.

What do you like?

**Comment by haroldangenent** [comment]
Well, there's only one reason I have ever needed something like this: when you need post type functionaliteit on a taxonomy term, but not on all taxonomies terms.

We have created [rich-taxonomy](https://github.com/trendwerk/rich-taxonomy) to do this, but it's a bit outdated and not fit to be backwards compatible with future versions. But it's probably a great way to start.

However one would create it, I believe it should be a separate plugin (not included in this one), to keep things light. So marking this as `wontfix` for now.
